#!/usr/bin/env bash
set -e
set -u
set -o pipefail


echo "Ensure you have the following dependencies installed:"
echo "kitty nvim fd ripgrep clangd yazi (and ya!)"
echo ""
echo "⚠️ WARNING: Running this script will override the following dotfiles:"
echo "   ~/.zshrc"
echo "   ~/.config/nvim/init.lua"
echo "   ~/.config/kitty/kitty.conf"
echo "   ~/.config/nvim/init.vim"
read -p "Type 'y' to continue: " confirm

if [[ "$confirm" != "y" ]]; then
  echo "Aborted."
  exit 1
fi

dotdir=$HOME/.dotfiles
cd $dotdir

# scripts
bindir=$HOME/.local/bin
mkdir -p $bindir
ln -sf $dotdir/bin/* $bindir

# zsh
zshdir=$HOME/.config/zsh
ln -sf $dotdir/zsh/.zshrc $HOME
touch $HOME/.zshrc_local
mkdir -p $zshdir
ln -sf $dotdir/zsh/aliases.zsh $zshdir

# kitty
kittydir=$HOME/.config/kitty
mkdir -p $kittydir
ln -sf $dotdir/kitty/kitty.conf $kittydir
kittytheme=https://raw.githubusercontent.com/dexpota/kitty-themes/master/themes/DotGov.conf
wget -N "$kittytheme" -P "$kittydir"

# neovim
nvimdir=$HOME/.config/nvim
mkdir -p $nvimdir
rm -f $nvimdir/init.vim # get rid of any other configs
ln -sf $dotdir/nvim/* $nvimdir
nvim +'PlugInstall --sync' +qa

# c++ templates
mkdir -p $HOME/Templates
rm -rf $HOME/Templates/empty_cpp
rm -rf $HOME/Templates/empty_sfml
ln -s $dotdir/Templates/empty_cpp $HOME/Templates
ln -s $dotdir/Templates/empty_sfml $HOME/Templates
ln -sf $dotdir/Templates/.clang-format $HOME/Templates
ln -sf $dotdir/Templates/.clang-tidy $HOME/Templates
ln -sf $dotdir/Templates/.gitignore $HOME/Templates


echo ""
echo "All done! You may want to run:"
echo " $ source $HOME/.zshrc"

cd - > /dev/null
