set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

# vim like navigation between windows
# shift + alt + {h, l}
bind -n M-H previous-window
bind -n M-L next-window

# Index windows and panes at 1
set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on

# transparent bar
set-option -g status-style bg=default
set-option -g status-bg default
set-option -g status-fg default
set-window-option -g window-status-current-style "bg=white,fg=black"
set-option -g status-position top
set-option -g status-justify centre

# get rid of * indicator for active window
set-window-option -g window-status-format " #I:#W "
set-window-option -g window-status-current-format " #I:#W "

# split in cwd
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Remove anything else from the status bar
set-option -g status-left ''
set-option -g status-right ''

# hide status bar unless more than 1 window
set-hook -g window-linked   'if -F "#{==:#{session_windows},1}" "set -g status off" "set -g status on"'
set-hook -g window-unlinked 'if -F "#{==:#{session_windows},1}" "set -g status off" "set -g status on"'

# initial state for a fresh session (1 window at start)
set-option -g status off

setw -g mouse on

run '$HOME/.tmux/plugins/tpm/tpm'
