"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$directory\
$git_branch\
$git_status\
$fill\
$username\
$hostname\
$line_break\
$character\
"""

[directory]
truncation_length = 8
truncation_symbol = '…/'
truncate_to_repo = false

[fill]
symbol = ' '

[git_branch]
format = '[$symbol$branch(:$remote_branch)](bold 34) '

[username]
format = '[$user]($style)'

[hostname]
format = '[@](bold blue)[$hostname]($style)'

[git_status]
modified = '*'
ahead = '⇡${count}'
diverged = '⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
format = '([\[$modified$ahead_behind\]](bold 208) )'
